#!/usr/bin/env bash
set -euo pipefail

SERVER_DIR="/opt/perun_speleo_spisskabela"

if [ "$PWD" = "$SERVER_DIR" ]; then
  git fetch --all
  git pull --ff-only origin main

  #php8.4 "$(command -v composer)" install --no-dev --optimize-autoloader

  php8.4 artisan config:clear
  php8.4 artisan route:clear
  php8.4 artisan view:clear
  #php8.4 artisan config:cache
  #php8.4 artisan route:cache
  #php8.4 artisan view:cache

  supervisorctl restart perun-laravel-worker:*

else
  npm run build

  git add -A
  git reset -- .env

  if [ -z "$(git status --porcelain)" ]; then
    echo "No changes to commit."
    exit 0
  fi

  git commit -a -m "Update build"
  git push
fi
